### ISSUE TITLE
大神，有个问题帮忙看看那呗

### ISSUE THREAD

**Issue by zhuchunyao164488421** [wenhuaijun/SearchPictureTool#2]
Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/maven/com.squareup.okio/okio/pom.xml
	File1: C:\Users\zcy\Desktop\SearchPictureTool-master\app\libs\com.umeng.message.lib_v2.5.0.jar
	File2: E:\AndroidDevTools\android-studio\gradle\gradle-2.10\caches\modules-2\files-2.1\com.squareup.okio\okio\1.6.0\98476622f10715998eacf9240d6b479f12c66143\okio-1.6.0.jar
用的是as2.1预览版  gradle 2.10  构建不了会报这个错
网上搜了方案不能解决，你的项目跑起来没问题吗？

**Comment by Jude95** [comment]
在项目Gradle中的android 节电内添加：
    packagingOptions {
        exclude 'META-INF/DEPENDENCIES.txt'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/dependencies.txt'
        exclude 'META-INF/LGPL2.1'
        exclude 'META-INF/maven/com.squareup.okio/okio/pom.xml'
        exclude 'META-INF/maven/com.squareup.okio/okio/pom.properties'
    }

**Comment by zhuchunyao164488421** [comment]
FATAL EXCEPTION: main
                                                                                           Process: com.example.administrator.searchpicturetool, PID: 1910
                                                                                           java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference
                                                                                               at java.lang.StringToReal.parseFloat(StringToReal.java:304)
                                                                                               at java.lang.Float.parseFloat(Float.java:306)
                                                                                               at java.lang.Float.valueOf(Float.java:343)
                                                                                               at com.example.administrator.searchpicturetool.view.JoyImageViewHolder.setData(JoyImageViewHolder.java:68)
                                                                                               at com.example.administrator.searchpicturetool.view.JoyImageViewHolder.setData(JoyImageViewHolder.java:34)
                                                                                               at com.jude.easyrecyclerview.adapter.RecyclerArrayAdapter.OnBindViewHolder(RecyclerArrayAdapter.java:472)
                                                                                               at com.jude.easyrecyclerview.adapter.RecyclerArrayAdapter.onBindViewHolder(RecyclerArrayAdapter.java:467)
                                                                                               at com.jude.easyrecyclerview.adapter.RecyclerArrayAdapter.onBindViewHolder(RecyclerArrayAdapter.java:49)
                                                                                               at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5217)
                                                                                               at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5250)
                                                                                               at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4487)
                                                                                               at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4363)
                                                                                               at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1961)
                                                                                               at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1370)
                                                                                               at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1333)
                                                                                               at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:562)
                                                                                               at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2900)
                                                                                               at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3071)
                                                                                               at android.view.View.layout(View.java:15596)
                                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4966)
                                                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
                                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
                                                                                               at com.jude.easyrecyclerview.swipe.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:546)
                                                                                               at android.view.View.layout(View.java:15596)
                                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4966)
                                                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
                                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
                                                                                               at android.view.View.layout(View.java:15596)
                                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4966)
                                                                                               at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1627)
                                                                                               at android.view.View.layout(View.java:15596)
                                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4966)
                                                                                               at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
                                                                                               at android.view.View.layout(View.java:15596)
                                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4966)
                                                                                               at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1037)
                                                                                               at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:747)
                                                                                               at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                                                               at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1156)
                                                                                               at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:760)
                                                                                               at android.view.View.layout(View.java:15596)
                                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4966)
                                                                                               at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
                                                                                               at android.view.View.layout(View.java:15596)
                                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4966)
                                                                                               at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1043)
                                                                                               at android.view.View.layout(View.java:15596)
                                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4966)
                                                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
                                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
                                                                                               at android.view.View.layout(View.java:15596)
                                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4966)
                                                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
                                                                                           	at android.widget.FrameLa
大神，换成了AS1.5 gradle 2.8 崩溃了
